version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: 159753
    cap_add:
      - SYS_NICE

networks:
  rabbitmq_go_net:
    driver: bridge